# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test3.proto',
  package='hello_word',
  syntax='proto3',
  serialized_pb=_b('\n\x0btest3.proto\x12\nhello_word\":\n\x05SayHi\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tsomething\x18\x02 \x01(\t\x12\x12\n\nextra_info\x18\x03 \x01(\tb\x06proto3')
)




_SAYHI = _descriptor.Descriptor(
  name='SayHi',
  full_name='hello_word.SayHi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hello_word.SayHi.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='something', full_name='hello_word.SayHi.something', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_info', full_name='hello_word.SayHi.extra_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['SayHi'] = _SAYHI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayHi = _reflection.GeneratedProtocolMessageType('SayHi', (_message.Message,), dict(
  DESCRIPTOR = _SAYHI,
  __module__ = 'test3_pb2'
  # @@protoc_insertion_point(class_scope:hello_word.SayHi)
  ))
_sym_db.RegisterMessage(SayHi)


# @@protoc_insertion_point(module_scope)
