# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testCreate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testCreate.proto',
  package='USV2Sever',
  syntax='proto3',
  serialized_pb=_b('\n\x10testCreate.proto\x12\tUSV2Sever\"\x8f\x01\n\x05\x41\x64min\x12\x0b\n\x03\x43md\x18\x01 \x01(\t\x12\t\n\x01U\x18\x02 \x01(\t\x12\t\n\x01P\x18\x03 \x01(\t\x12$\n\x05newUs\x18\x04 \x03(\x0b\x32\x15.USV2Sever.Admin.User\x1a=\n\x04User\x12\t\n\x01N\x18\x01 \x01(\t\x12\t\n\x01P\x18\x02 \x01(\t\x12\r\n\x05Level\x18\x03 \x01(\x05\x12\x10\n\x08USVsname\x18\x04 \x03(\tB!\xaa\x02\x1eOstar.Protobuf.USV2Sever.Adminb\x06proto3')
)




_ADMIN_USER = _descriptor.Descriptor(
  name='User',
  full_name='USV2Sever.Admin.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='N', full_name='USV2Sever.Admin.User.N', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='P', full_name='USV2Sever.Admin.User.P', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Level', full_name='USV2Sever.Admin.User.Level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='USVsname', full_name='USV2Sever.Admin.User.USVsname', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=175,
)

_ADMIN = _descriptor.Descriptor(
  name='Admin',
  full_name='USV2Sever.Admin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='USV2Sever.Admin.Cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='U', full_name='USV2Sever.Admin.U', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='P', full_name='USV2Sever.Admin.P', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newUs', full_name='USV2Sever.Admin.newUs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADMIN_USER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=175,
)

_ADMIN_USER.containing_type = _ADMIN
_ADMIN.fields_by_name['newUs'].message_type = _ADMIN_USER
DESCRIPTOR.message_types_by_name['Admin'] = _ADMIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Admin = _reflection.GeneratedProtocolMessageType('Admin', (_message.Message,), dict(

  User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
    DESCRIPTOR = _ADMIN_USER,
    __module__ = 'testCreate_pb2'
    # @@protoc_insertion_point(class_scope:USV2Sever.Admin.User)
    ))
  ,
  DESCRIPTOR = _ADMIN,
  __module__ = 'testCreate_pb2'
  # @@protoc_insertion_point(class_scope:USV2Sever.Admin)
  ))
_sym_db.RegisterMessage(Admin)
_sym_db.RegisterMessage(Admin.User)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\036Ostar.Protobuf.USV2Sever.Admin'))
# @@protoc_insertion_point(module_scope)
